"""
stock_catalyst_bot.py
Posts today's top WaveTrend bull cross picks to Discord with news catalysts.
Reads wt_scans/wt_bullcross_latest.md (local, generated by wt_bullcross_scanner.py).
Fetches news via NewsAPI using each stock's business label for better query quality.
Posts via Discord webhook (DISCORD_WEBHOOK_URL from Windows user env or .env).
"""

import os
import re
import sys
import requests
from datetime import datetime, timezone, timedelta
from pathlib import Path
from dotenv import load_dotenv

IST = timezone(timedelta(hours=5, minutes=30))

ROOT = Path(__file__).parent
load_dotenv(ROOT / ".env")

# Webhook URL: Windows user env var takes precedence, then .env DISCORD_WEBHOOK_URL
DISCORD_WEBHOOK = os.environ.get("DISCORD_WEBHOOK_URL", "")
NEWSAPI_KEY = os.environ["NEWSAPI_KEY"]

WT_MD = ROOT / "wt_scans" / "wt_bullcross_latest.md"
NEWSAPI_URL = "https://newsapi.org/v2/everything"

# Sort: squeeze first, then rank desc (lower RANK_ORDER value = higher priority)
RANK_ORDER = {5: 0, 4: 1, 3: 2, 2: 3, 1: 4}
MAX_STOCKS = 12  # keeps Discord message under 2000 chars


# ── parser ────────────────────────────────────────────────────────────────────


def parse_md(path: Path) -> tuple[str, str, list[dict]]:
    """Return (scan_date, total_signals, stocks_list) deduplicated, priority-sorted."""
    text = path.read_text(encoding="utf-8")

    m = re.search(r"# WaveTrend Bull Cross Scan — (\d{4}-\d{2}-\d{2})", text)
    scan_date = m.group(1) if m else datetime.now(IST).strftime("%Y-%m-%d")

    m2 = re.search(r"\*\*Total bull crosses today: (\d+)\*\*", text)
    total = m2.group(1) if m2 else "?"

    row_re = re.compile(
        r"\|\s*\[(\w+)\]\([^)]+\)\s*\|"  # symbol
        r"([^|]*)\|"  # label
        r"([^|]*)\|"  # signal
        r"\s*(\d+)\s*\|"  # rank
        r"[^|]*\|[^|]*\|"  # WT1, WT2
        r"([^|]*)\|"  # ZL arrow
        r"[^|]*\|[^|]*\|"  # ZL days, ZL chg%
        r"\s*([✓—])\s*\|"  # Sqz
        r"\s*([✓—])\s*\|"  # PPV
        r"[^|]*\|"  # RS
        r"\s*([+\-\d.]+%)\s*\|"  # Day chg
        r"\s*([\d,.]+)\s*\|"  # Close
    )

    seen = set()
    stocks = []
    for m in row_re.finditer(text):
        symbol = m.group(1).strip()
        if symbol in seen:
            continue
        seen.add(symbol)
        stocks.append(
            {
                "symbol": symbol,
                "label": m.group(2).strip(),
                "rank": int(m.group(4)),
                "zl_up": "↑" in m.group(5),
                "sqz": m.group(6).strip() == "✓",
                "ppv": m.group(7).strip() == "✓",
                "day_chg": m.group(8).strip(),
                "close": m.group(9).strip(),
            }
        )

    stocks.sort(key=lambda s: (not s["sqz"], RANK_ORDER.get(s["rank"], 9)))
    return scan_date, total, stocks


# ── news ──────────────────────────────────────────────────────────────────────

# Indian financial news domains — restricts NewsAPI results to India-context sources
_INDIA_DOMAINS = ",".join(
    [
        "economictimes.indiatimes.com",
        "moneycontrol.com",
        "livemint.com",
        "business-standard.com",
        "financialexpress.com",
        "ndtvprofit.com",
        "thehindu.com",
        "reuters.com",
    ]
)


def get_news(symbol: str, label: str) -> list[str]:
    """
    Return up to 3 India-relevant headline strings.
    Query: NSE symbol + key label words, restricted to Indian financial domains.
    Falls back to label-only query if symbol search returns nothing.
    """
    # Strip generic noise; keep sector/product keywords
    label_keywords = re.sub(
        r"\b(manufacturing|production|services|company|limited|ltd|and|for|of|in|the)\b",
        "",
        label,
        flags=re.I,
    ).strip()
    label_keywords = re.sub(r"\s+", " ", label_keywords)[:50]

    # Primary query: symbol (unique NSE ticker) + "NSE" for stock context
    # Fallback query: label keywords + "India" for sector context
    for query in [f"{symbol} NSE", f"{label_keywords} India stock"]:
        query = query.strip()
        if not query:
            continue
        try:
            resp = requests.get(
                NEWSAPI_URL,
                params={
                    "q": query,
                    "domains": _INDIA_DOMAINS,
                    "language": "en",
                    "sortBy": "publishedAt",
                    "pageSize": 5,
                    "apiKey": NEWSAPI_KEY,
                },
                timeout=6,
            )
            if resp.status_code == 200:
                headlines = []
                for art in resp.json().get("articles", [])[:3]:
                    title = re.sub(
                        r"\s*-\s*[^-]{1,40}$", "", art.get("title") or ""
                    ).strip()
                    if title:
                        headlines.append(title[:110])
                if headlines:
                    return headlines
        except Exception:
            pass

    return ["No recent news — WT bull cross signal"]


# ── discord ───────────────────────────────────────────────────────────────────


def build_messages(scan_date: str, total: str, stocks: list[dict]) -> list[str]:
    """
    Plain-text Discord messages grouped by signal quality.
    Works on mobile. Each message ≤1950 chars.

    Groups:
      🔥 Squeeze Breakout  — SQZ flag set
      ⚡ PPV Confirmed     — PPV, no squeeze
      📈 Bull Cross        — plain cross
    """
    now_ist = datetime.now(IST).strftime("%H:%M IST")

    sqz = [s for s in stocks if s["sqz"]][:10]
    ppv = [s for s in stocks if not s["sqz"] and s["ppv"]][:5]
    plain = [s for s in stocks if not s["sqz"] and not s["ppv"]][:5]

    def fmt_group(header: str, group: list[dict]) -> str:
        if not group:
            return ""
        lines = [f"\n**{header}**"]
        for s in group:
            headlines = get_news(s["symbol"], s["label"])
            tags = ("↑ZL " if s["zl_up"] else "") + ("⚡PPV " if s["ppv"] else "")
            news_lines = "\n".join(
                f"> {'📰' if i == 0 else '  ↳'} {h}" for i, h in enumerate(headlines)
            )
            lines.append(
                f"> ### {s['symbol']}  ₹{s['close']} · **{s['day_chg']}**  {tags}\n"
                f"> {s['label']}\n"
                f"{news_lines}\n"
                f"> ​"  # zero-width space → blank blockquote line = visual gap
            )
        return "\n".join(lines)

    header = (
        f"📊 **WaveTrend Bull Cross · {scan_date} · {now_ist}**\n"
        f"`{total} signals` · 🔥 squeeze · ⚡ pocket-pivot · ↑ZL rising\n"
        f"{'─' * 36}"
    )

    body = (
        fmt_group("🔥 Squeeze Breakout", sqz)
        + fmt_group("⚡ PPV Confirmed", ppv)
        + fmt_group("📈 Bull Cross", plain)
    )

    # Split into ≤1950-char chunks at group boundaries
    full = header + body
    messages = []
    while len(full) > 1950:
        cut = full.rfind("\n", 0, 1950)
        if cut == -1:
            cut = 1950
        messages.append(full[:cut])
        full = full[cut:].lstrip("\n")
    if full:
        messages.append(full)
    return messages


def discord_post_payload(payload: dict) -> None:
    resp = requests.post(DISCORD_WEBHOOK, json=payload, timeout=15)
    resp.raise_for_status()


def discord_post_text(content: str) -> None:
    resp = requests.post(DISCORD_WEBHOOK, json={"content": content}, timeout=15)
    resp.raise_for_status()


# ── main ──────────────────────────────────────────────────────────────────────


def main():
    if not DISCORD_WEBHOOK:
        print("ERROR: DISCORD_WEBHOOK_URL not set. Add it via setx or .env.")
        sys.exit(1)

    if not WT_MD.exists():
        print(f"ERROR: {WT_MD} not found. Run wt_bullcross_scanner.py first.")
        sys.exit(1)

    print(f"Parsing {WT_MD} ...")
    scan_date, total, stocks = parse_md(WT_MD)
    print(f"  {len(stocks)} unique stocks (total signals: {total})")

    if not stocks:
        print("No stocks — nothing to post.")
        sys.exit(0)

    sqz = sum(1 for s in stocks if s["sqz"])
    ppv = sum(1 for s in stocks if not s["sqz"] and s["ppv"])
    print(f"  Groups: {sqz} squeeze  {ppv} PPV  {len(stocks)-sqz-ppv} plain")

    print("Building messages + fetching news ...")
    messages = build_messages(scan_date, total, stocks)

    print(f"Posting {len(messages)} message(s) to Discord ...")
    for i, msg in enumerate(messages, 1):
        discord_post_text(msg)
        print(f"  [{i}/{len(messages)}] {len(msg)} chars")
    print(f"Done — {datetime.now(IST).strftime('%Y-%m-%d %H:%M IST')}")


if __name__ == "__main__":
    main()
