study("DARVAS BOX", overlay=true, shorttitle="DARVAS")
boxp = input(5, "BOX LENGTH")

LL = lowest(low, boxp)
k1 = highest(high, boxp)
k2 = highest(high, boxp-1)
k3 = highest(high, boxp-2)

NH = valuewhen(high > k1[1], high, 0)
box1 = k3 < k2
TopBox = valuewhen(barssince(high > k1[1]) == boxp-2 and box1, NH, 0)
BottomBox = valuewhen(barssince(high > k1[1]) == boxp-2 and box1, LL, 0)

plot(TopBox, linewidth=1, color=green, title="TBbox")
plot(BottomBox, linewidth=1, color=red, title="BBbox")
